name: Check Source Repository
on:
  schedule:
    - cron: "*/30 * * * *" # Check every 30 minutes
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check for updates
        run: |
          LAST_COMMIT=$(curl -s "https://api.github.com/repos/TheSpeedX/PROXY-List/commits/master" | jq -r .sha)
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV

          if [ ! -f "/tmp/last_commit.txt" ] || [ "$(cat /tmp/last_commit.txt)" != "$LAST_COMMIT" ]; then
            echo $LAST_COMMIT > /tmp/last_commit.txt
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              ${{ github.api_url }}/repos/${{ github.repository }}/dispatches \
              --data '{"event_type":"proxy_list_updated"}'
          fi

permissions:
  contents: write
  actions: write
